// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqzxzfxlgywtghdvoask.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxenh6ZnhsZ3l3dGdoZHZvYXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTkzMTAsImV4cCI6MjA2OTI3NTMxMH0.5Ww6zLyZC5j4qzpgj7GXfESgR9svFf8u90QqfqP036U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});